// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/configuration.model.dart';
import 'models/game.model.dart';
import 'models/player.model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 3321156729956570825),
      name: 'Configuration',
      lastPropertyId: const obx_int.IdUid(2, 9171245532256701350),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6569757577443930507),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 9171245532256701350),
            name: 'sensibility',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 4554995745373457152),
      name: 'Game',
      lastPropertyId: const obx_int.IdUid(3, 2897989111957518467),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5461361411414513754),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 714234118948441198),
            name: 'round',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2897989111957518467),
            name: 'sesiblitiy',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 2179733479965591908),
      name: 'Player',
      lastPropertyId: const obx_int.IdUid(3, 8787411259697888914),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3849161135491977204),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6490421171268617785),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8787411259697888914),
            name: 'score',
            type: 8,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(3, 2179733479965591908),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Configuration: obx_int.EntityDefinition<Configuration>(
        model: _entities[0],
        toOneRelations: (Configuration object) => [],
        toManyRelations: (Configuration object) => {},
        getId: (Configuration object) => object.id,
        setId: (Configuration object, int id) {
          object.id = id;
        },
        objectToFB: (Configuration object, fb.Builder fbb) {
          final sensibilityOffset = fbb.writeString(object.sensibility);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, sensibilityOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Configuration()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..sensibility = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '');

          return object;
        }),
    Game: obx_int.EntityDefinition<Game>(
        model: _entities[1],
        toOneRelations: (Game object) => [],
        toManyRelations: (Game object) => {},
        getId: (Game object) => object.id,
        setId: (Game object, int id) {
          object.id = id;
        },
        objectToFB: (Game object, fb.Builder fbb) {
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.round);
          fbb.addInt64(2, object.sesiblitiy);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Game()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..round = const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0)
            ..sesiblitiy =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);

          return object;
        }),
    Player: obx_int.EntityDefinition<Player>(
        model: _entities[2],
        toOneRelations: (Player object) => [],
        toManyRelations: (Player object) => {},
        getId: (Player object) => object.id,
        setId: (Player object, int id) {
          object.id = id;
        },
        objectToFB: (Player object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addFloat64(2, object.score);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final object = Player(idParam, nameParam)
            ..score =
                const fb.Float64Reader().vTableGet(buffer, rootOffset, 8, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Configuration] entity fields to define ObjectBox queries.
class Configuration_ {
  /// See [Configuration.id].
  static final id =
      obx.QueryIntegerProperty<Configuration>(_entities[0].properties[0]);

  /// See [Configuration.sensibility].
  static final sensibility =
      obx.QueryStringProperty<Configuration>(_entities[0].properties[1]);
}

/// [Game] entity fields to define ObjectBox queries.
class Game_ {
  /// See [Game.id].
  static final id = obx.QueryIntegerProperty<Game>(_entities[1].properties[0]);

  /// See [Game.round].
  static final round =
      obx.QueryIntegerProperty<Game>(_entities[1].properties[1]);

  /// See [Game.sesiblitiy].
  static final sesiblitiy =
      obx.QueryIntegerProperty<Game>(_entities[1].properties[2]);
}

/// [Player] entity fields to define ObjectBox queries.
class Player_ {
  /// See [Player.id].
  static final id =
      obx.QueryIntegerProperty<Player>(_entities[2].properties[0]);

  /// See [Player.name].
  static final name =
      obx.QueryStringProperty<Player>(_entities[2].properties[1]);

  /// See [Player.score].
  static final score =
      obx.QueryDoubleProperty<Player>(_entities[2].properties[2]);
}
